port: 4003
highlighter: rouge
gems:
  - jekyll-sitemap
ga: "UA-55584370-11"

includes:
- _includes_custom

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      last_modified_at: "2018-04-11"
